// react-test/src/App.tsx
import { DatePicker, Button, Tooltip, Table } from 'antd'
import { FC, useEffect, useMemo } from 'react'
import { useStore, useConst } from './Store.ts'
import { useShallow } from 'zustand/react/shallow'
import { createStyles, css, cx } from 'antd-style'
import dayjs from 'dayjs'
import {
  Color, UpOrDown, ArrowSvgName, getData, genPrice, monthPlus,
  toFixedNumber, removeMilli, toFixedString, milliTimeToStringTime,
  DataType1, DataType2, DataType3, DataType4, getFonts
} from './Lib.ts'

const { Column } = Table
const { setState } = useStore

async function init(): Promise<void> {
  const themeMedia = window.matchMedia("(prefers-color-scheme: light)")
  setState({ isLight: themeMedia.matches })
  themeMedia.onchange = (e) => setState({ isLight: e.matches })
  const getPrice = async () => {
    for await (const i of genPrice()) {
      const price = toFixedNumber(i.price, 2)
      document.title = toFixedString(i.price, 2)
      setState((state) => ({ price, priceOld: state.price }))
    }
  }
  getPrice()
  const [resData] = await Promise.all([getData(), getFonts()])
  setState((state) => ({
    getData: resData,
    price: toFixedNumber(state.price ?? resData.nowPrice, 2),
    priceOld: toFixedNumber(state.priceOld ?? resData.shortPrice, 2),
    isLoading: false,
  }))
}

const ArrowSvg: FC<{ name: string }> = ({ name }) => {
  if (name === ArrowSvgName.rightUpArrow) {
    return (
      <svg style={{ color: Color.green }} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
        viewBox="0 0 16 16">
        <path fillRule="evenodd"
          d="M14 2.5a.5.5 0 0 0-.5-.5h-6a.5.5 0 0 0 0 1h4.793L2.146 13.146a.5.5 0 0 0 .708.708L13 3.707V8.5a.5.5 0 0 0 1 0v-6z" />
      </svg>
    )
  }
  if (name === ArrowSvgName.rightDownArrow) {
    return (
      <svg style={{ color: Color.red }} xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
        viewBox="0 0 16 16">
        <path fillRule="evenodd"
          d="M14 13.5a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1 0-1h4.793L2.146 2.854a.5.5 0 1 1 .708-.708L13 12.293V7.5a.5.5 0 0 1 1 0v6z" />
      </svg>
    )
  }
  if (name === ArrowSvgName.rightArrow) {
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
        viewBox="0 0 16 16">
        <path
          d="M6 12.796V3.204L11.481 8 6 12.796zm.659.753 5.48-4.796a1 1 0 0 0 0-1.506L6.66 2.451C6.011 1.885 5 2.345 5 3.204v9.592a1 1 0 0 0 1.659.753z" />
      </svg>
    )
  }
  if (name === ArrowSvgName.leftArrow) {
    return (
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
        viewBox="0 0 16 16">
        <path
          d="M10 12.796V3.204L4.519 8 10 12.796zm-.659.753-5.48-4.796a1 1 0 0 1 0-1.506l5.48-4.796A1 1 0 0 1 11 3.204v9.592a1 1 0 0 1-1.659.753z" />
      </svg>
    )
  }
  return <></>
}

const RightUpArrow: FC = () => {
  return (<ArrowSvg name={ArrowSvgName.rightUpArrow} />)
}

const RightDownArrow: FC = () => {
  return (<ArrowSvg name={ArrowSvgName.rightDownArrow} />)
}

const ArrowButtonStyle = createStyles({
  ArrowButton: css`
    width: 40px;
    height: 32px;
    padding: 0;
  `
})

const RightArrowButton: FC = () => {
  const { styles } = ArrowButtonStyle()
  return (
    <Button className={styles.ArrowButton}>
      <ArrowSvg name={ArrowSvgName.rightArrow} />
    </Button>
  )
}

const LeftArrowButton: FC = () => {
  const { styles } = ArrowButtonStyle()
  return (
    <Button className={styles.ArrowButton}>
      <ArrowSvg name={ArrowSvgName.leftArrow} />
    </Button>
  )
}

const TimeAndPriceStyle = createStyles((_, props: {
  isError: boolean; upOrDown: UpOrDown
}) => {
  const priceColor = props.upOrDown === UpOrDown.up ? Color.green :
    props.upOrDown === UpOrDown.down ? Color.red : 'inherit'
  return {
    timeColor: css`
      color: ${props.isError ? Color.red : Color.green};
    `,
    priceColor: css`
      color: ${priceColor};
  `,
  }
})

const FlexStyle = createStyles(() => {
  return {
    fsbc: css`
      display: flex;
      justify-content: space-between;
      align-items: center;
    `,
    fcc: css`
      display: flex;
      justify-content: center;
      align-items: center;
    `,
    fco: css`
      display: flex;
      flex-direction: column;
    `,
    fro: css`
      display: flex;
      flex-direction: row;
    `,
    c: css`
      width: ${useConst.width};
      padding-left: ${useConst.paddingLeft};
      padding-right: ${useConst.paddingRight};
    `,
    column: css`
      height: 30px;
      font-family: TAHOMA, Tahoma, Helvetica, Arial, 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;
    `,
    ff: css`
      font-family: TAHOMA, Tahoma, Helvetica, Arial, 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;
    `,
  }
})

const AppStyle = createStyles((_, props: { isLight: boolean }) => {
  return {
    app: css`
      display: flex;
      flex-direction: column;
      align-items: center;
      background-color: ${props.isLight ? Color.white : Color.black};
      font-family: TAHOMA, Tahoma, Helvetica, Arial, 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif;
      color: ${props.isLight ? Color.black : Color.white};
    `,
    loading: css`
      height: 100dvh;
      display: flex;
      justify-content: center;
      align-items: center;
    `,
    loader: css`
      @keyframes load8 {
        0% {
          transform: rotate(0deg);
        }

        100% {
          transform: rotate(360deg);
        }
      }
      width: 60px;
      height: 60px;
      border-radius: 50%;
      border-top: 4px solid #e2e2e2;
      border-right: 4px solid #e2e2e2;
      border-bottom: 4px solid #e2e2e2;
      border-left: 4px solid #409eff;
      animation: load8 1.1s infinite linear;
    `,
  }
})

const TimeAndPrice: FC = () => {
  const { upOrDown, getData, price } = useStore(useShallow((state) => ({
    upOrDown: state.upOrDown, getData: state.getData, price: state.price,
  })))
  const isError = (getData?.resErrorLogArray?.length ?? 0) > 0
  const { styles: flexStyle } = FlexStyle()
  const { styles: tapStyle } = TimeAndPriceStyle({ isError, upOrDown: upOrDown })
  return (
    <div style={{ userSelect: 'none' }} className={cx(flexStyle.fsbc, flexStyle.c)}>
      <Tooltip mouseEnterDelay={0} title={<div className={flexStyle.ff}>{removeMilli(getData?.startTime)}</div>} >
        <div className={tapStyle.timeColor}>{removeMilli(getData?.analyseTime)}</div>
      </Tooltip>
      <Tooltip mouseEnterDelay={0} title={<div className={flexStyle.ff}>
        <div className={flexStyle.fsbc}>
          <div style={{ whiteSpace: 'pre' }}>shortPrice : </div>
          <div>{getData?.shortPrice ? toFixedString(getData?.shortPrice, 2) : ''}</div>
        </div>
        <div className={flexStyle.fsbc}>
          <div style={{ whiteSpace: 'pre' }}>longPrice : </div>
          <div>{getData?.longPrice ? toFixedString(getData?.longPrice, 2) : ''}</div>
        </div>
      </div>}>
        <div className={cx(flexStyle.fcc, flexStyle.fro)}>
          <span style={{ whiteSpace: 'pre' }}>BTC : </span>
          <span className={tapStyle.priceColor}>{price ? toFixedString(price, 1) : ''}</span>
          {upOrDown === UpOrDown.up ? <RightUpArrow /> : ''}
          {upOrDown === UpOrDown.down ? <RightDownArrow /> : ''}
        </div>
      </Tooltip>
    </div>
  )
}

const MonthPicker: FC = () => {
  const { styles: flexStyle } = FlexStyle()
  const { yearMonth } = useStore(useShallow((state) => ({
    yearMonth: state.yearMonth
  })))
  const getYearMonth = (data?: Date) => {
    return milliTimeToStringTime(data?.getTime() ?? new Date().getTime()).slice(0, 7)
  }
  const onChange = (e: any) => {
    setState((state) => {
      const date = e?.$d ?? null
      if (date) {
        state.yearMonth = getYearMonth(date)
      } else {
        state.yearMonth = ''
      }
    })
  }
  useEffect(() => {
    setState((state) => {
      if (!state.yearMonth) {
        state.yearMonth = getYearMonth()
      }
    })
  }, [yearMonth])
  const onClickLeft = () => {
    setState((state) => {
      state.yearMonth = monthPlus(yearMonth || getYearMonth(), -1)
    })
  }
  const onClickRight = () => {
    setState((state) => {
      state.yearMonth = monthPlus(yearMonth || getYearMonth(), 1)
    })
  }
  const yearMonthValue = useMemo(() => yearMonth ? dayjs(yearMonth) : '', [yearMonth])
  return (<div className={cx(flexStyle.fro, flexStyle.c, flexStyle.fsbc)}>
    <div>
      <DatePicker
        style={{ width: '220px' }}
        value={yearMonthValue}
        onChange={onChange} picker="month" />
    </div>
    <div className={cx(flexStyle.fro)}>
      <div onClick={onClickLeft}>
        <LeftArrowButton />
      </div>
      <div style={{ width: '15px' }}></div>
      <div onClick={onClickRight}>
        <RightArrowButton />
      </div>
    </div>
  </div>)
}

const Table1: FC = () => {
  const { tableData1 } = useStore(useShallow((state) => ({ tableData1: state.tableData1 })))
  const { styles: flexStyle } = FlexStyle()
  return (
    <div className={flexStyle.c}>
      <Table<DataType1> dataSource={tableData1} size="small" pagination={false} bordered>
        <Column className={flexStyle.column} align="center" title="month" key="month" dataIndex="month" />
        <Column className={flexStyle.column} align="center" title="leverage" key="leverage" dataIndex="leverage" />
        <Column className={flexStyle.column} align="center" title="rate" key="rate" dataIndex="rate" render={(_, item) => (<>
          <Tooltip mouseEnterDelay={0} placement="left" title={<div className={flexStyle.ff}>
            <div style={{ whiteSpace: 'pre' }}>rate2 : {item.rate2}</div>
            <div style={{ whiteSpace: 'pre' }}>rateAvg : {item.rateAvg}</div>
          </div>}>
            <div>{item.rate}</div>
          </Tooltip>
        </>)} />
      </Table>
    </div>
  )
}

const Table2: FC = () => {
  const { styles: flexStyle } = FlexStyle()
  const { tableData2, getData } = useStore(useShallow((state) => ({
    tableData2: state.tableData2, getData: state.getData
  })))
  return (
    <div className={flexStyle.c}>
      <Table<DataType2> dataSource={tableData2} size="small" pagination={false} bordered>
        <Column className={flexStyle.column} align="center" title={`time(${getData?.analyseTime?.slice(24, 27) ?? ''})`} key="time" dataIndex="time" />
        <Column className={flexStyle.column} align="center" title="price" key="price" dataIndex="price" render={(_, item) => (<>
          <Tooltip mouseEnterDelay={0} placement="left" title={<div className={flexStyle.ff}>
            {item.avg ? <div style={{ whiteSpace: 'pre' }}>avg : {item.avg}</div> : ''}
            {item.avgChg ? <div style={{ whiteSpace: 'pre' }}>avgChg : {item.avgChg}</div> : ''}
            {item.status2 ? <div style={{ whiteSpace: 'pre' }}>status2 : {item.status2}</div> : ''}
            {item.rate2 ? <div style={{ whiteSpace: 'pre' }}>rate2 : {item.rate2}</div> : ''}
          </div>}>
            <div>{item.price}</div>
          </Tooltip>
        </>)} />
        <Column className={flexStyle.column} align="center" title="status" key="status" dataIndex="status" />
        <Column className={flexStyle.column} align="center" title={() => (
          <div style={{ userSelect: 'none' }} onDoubleClick={() => { setState((state) => { state.isShowAll = !state.isShowAll }) }}>rate</div>
        )} key="rate" dataIndex="rate" />
      </Table>
    </div>
  )
}

const Table3: FC = () => {
  const { styles: flexStyle } = FlexStyle()
  const { tableData3 } = useStore(useShallow((state) => ({ tableData3: state.tableData3 })))
  return (<div className={flexStyle.c}>
    <Table<DataType3> dataSource={tableData3} size="small" pagination={false} bordered>
      <Column width={100} className={flexStyle.column} align="center" title="lastNMonth" key="lastNMonth" dataIndex="lastNMonth" render={(_, item) => (<>
        <Tooltip mouseEnterDelay={0} placement="right" title={<div className={flexStyle.ff}>
          {item.rate2 ? <div style={{ whiteSpace: 'pre' }}>rate2 : {item.rate2}</div> : ''}
        </div>}>
          <div>{item.lastNMonth}</div>
        </Tooltip>
      </>)} />
      <Column className={flexStyle.column} align="center" title="rate" key="rate" dataIndex="rate" />
      <Column width={100} className={flexStyle.column} align="center" title="avgMonth" key="avgMonth" dataIndex="avgMonth" />
    </Table>
  </div>)
}

const Table4: FC = () => {
  const { styles: flexStyle } = FlexStyle()
  const { tableData4 } = useStore(useShallow((state) => ({ tableData4: state.tableData4 })))
  return (<div className={flexStyle.c}>
    <Table<DataType4> dataSource={tableData4} size="small" pagination={false} bordered>
      <Column width={118} className={flexStyle.column} align="center" title="year" key="year" dataIndex="year" render={(_, item) => (<>
        <Tooltip mouseEnterDelay={0} placement="right" title={<div className={flexStyle.ff}>
          {item.rate2 ? <div style={{ whiteSpace: 'pre' }}>rate2 : {item.rate2}</div> : ''}
        </div>}>
          <div>{item.year}</div>
        </Tooltip>
      </>)} />
      <Column className={flexStyle.column} align="center" title="rate" key="rate" dataIndex="rate" />
      <Column width={118} className={flexStyle.column} align="center" title="avgMonth" key="avgMonth" dataIndex="avgMonth" />
    </Table>
  </div>)
}

const App: FC = () => {
  const {
    isLight, price, priceOld, yearMonth, updateUpOrDown, updateShowData, isLoading, isShowAll
  } = useStore(useShallow((state) => {
    const {
      isLight, price, priceOld, yearMonth, updateUpOrDown, updateShowData, isLoading, isShowAll
    } = state
    return {
      isLight, price, priceOld, yearMonth, updateUpOrDown, updateShowData, isLoading, isShowAll
    }
  }))
  useEffect(() => { init() }, [])
  useEffect(() => {
    const root = document.getElementById('root')
    if (root) {
      root.style.backgroundColor = isLight ? Color.white : Color.black
    }
  }, [isLight])
  useEffect(() => { updateUpOrDown() }, [price, priceOld])
  useEffect(() => { if (!isLoading || yearMonth) { updateShowData() } }, [isLoading, yearMonth, isShowAll])
  const { styles: appStyle } = AppStyle({ isLight })
  return (
    <div className={appStyle.app}>
      {isLoading ? <div className={appStyle.loading}>
        <div className={appStyle.loader}></div>
      </div> : (<>
        <div style={{ height: '20px' }}></div>
        <TimeAndPrice />
        <div style={{ height: '20px' }}></div>
        <MonthPicker />
        <div style={{ height: '20px' }}></div>
        <div><Table1 /></div>
        <div style={{ height: '20px' }}></div>
        <div><Table2 /></div>
        <div style={{ height: '20px' }}></div>
        <div><Table3 /></div>
        <div style={{ height: '20px' }}></div>
        <div><Table4 /></div>
        <div style={{ height: '400px' }}></div>
      </>)
      }
    </div>
  )
}

export default App

// vue-test/src/App.vue
<script setup lang="ts">
import * as Lib from './Lib.ts'
import { onMounted, reactive, watchEffect } from 'vue'
import { Status, Color } from './Lib.ts'
import Table from './components/Table.vue'
import TimeAndPrice from './components/TimeAndPrice.vue'
import Loading from './components/Loading.vue'
import MonthPicker from './components/MonthPicker.vue'

let width = 355
let leverage = 6
let resData = {} as {
  analyseTime: string,
  startTime: string,
  dataMap1: Map<string, Array<{ time: string, price: number, priceAvg: number, priceAvgChg: number, state: Status, s: number }>>,
  dataMap2: Map<string, Array<{ time: string, price: number, priceAvg: number, priceAvgChg: number, state: Status, s: number }>>,
  dataMapMonthS1: Map<string, number>,
  dataMapMonthS2: Map<string, number>,
  dataMapYearSMonthAvgS1: Map<string, { yearTotalS: number, monthAvgS: number }>,
  dataMapYearSMonthAvgS2: Map<string, { yearTotalS: number, monthAvgS: number }>,
  lastNMonthSPerSixMonth1: Array<{ lastNMonth: number, totalS: number, monthAvgS: number }>,
  lastNMonthSPerSixMonth2: Array<{ lastNMonth: number, totalS: number, monthAvgS: number }>,
  resErrorLogArray: Array<{ time: string, from: string, msg: string }>,
  resInfoLogArray: Array<{ time: string, from: string, msg: string }>,
  resPriceLog: { nowPrice: number, shortPrice: number, longPrice: number, time: string },
}

let state = reactive({
  isLoading: true,
  isShowAll: true,
  currentMonth: Lib.getNowStringTime().slice(0, 7),
  priceArray: [] as Array<{ time: string, price: number }>,
  priceColor: Color.black,
  time: '',
  timeColor: Color.black,
  resErrorLogArray: [] as Array<{ time: string, from: string, msg: string }>,
  resInfoLogArray: [] as Array<{ time: string, from: string, msg: string }>,
} as {
  isLoading: boolean
  isShowAll: boolean
  currentMonth: string
  priceArray: Array<{ time: string, price: number }>
  priceColor: Color
  time: string
  timeColor: Color
  resErrorLogArray: Array<{ time: string, from: string, msg: string }>
  resInfoLogArray: Array<{ time: string, from: string, msg: string }>
  resPriceLog: { nowPrice: number, shortPrice: number, longPrice: number, time: string },
  table1: any
  table2: any
  table3: any
  table4: any
})

onMounted(async () => {
  await getData()
  setTable1()
  setTable2()
  setTable3()
  setTable4()
})

watchEffect(async () => {
  ;[state.currentMonth, state.isShowAll];
  if (Object.keys(resData).length === 0) {
    return
  }
  setTable1()
  setTable2()
})

watchEffect(() => {
  if (state.priceArray.length >= 2) {
    let price1 = state.priceArray.at(-1)!!.price
    let price2 = state.priceArray.at(-2)!!.price
    if (price1 > price2) {
      state.priceColor = Color.green
    }
    if (price1 < price2) {
      state.priceColor = Color.red
    }
  }
})

function setTable1() {
  let data = resData.dataMapMonthS1.get(state.currentMonth)
  let data2 = resData.dataMapMonthS2.get(state.currentMonth)
  let fields1 = [
    { key: 'month', label: 'month', align: 'center' },
    { key: 'leverage', label: 'leverage', align: 'center' },
    { key: 'rate', label: 'rate', align: 'center' },
  ]
  let items1 = [
    {
      month: { value: state.currentMonth },
      leverage: { value: leverage },
      rate: {
        value: Lib.toFixedString(data ? data : 1, 3),
        popover: { rate2: Lib.toFixedString(data2 ? data2 : 1, 3) },
        placement: 'left',
      },
    },
  ]
  let table1 = { width, border: true, fields: fields1, items: items1 }
  state.table1 = table1
}

function setTable2() {
  let fields2 = [
    { key: 'time', label: `time(${resData.analyseTime.slice(24, 27)})`, width: 140 },
    { key: 'price', label: 'price', align: 'center', width: 80 },
    { key: 'status', label: 'status', align: 'center', width: 70 },
    {
      key: 'rate', label: 'rate', align: 'center', width: 65, dblclick: () => {
        state.isShowAll = !state.isShowAll
      },
    },
  ]
  let items2: any[] = []
  let lastMonth = Lib.monthPlus(state.currentMonth, -1)
  let lastMonthLast = resData.dataMap1.get(lastMonth)?.at(-1)
  if (resData.dataMap1.get(state.currentMonth) && resData.dataMap2.get(state.currentMonth)) {
    for (let i = 0; i < resData.dataMap1.get(state.currentMonth)!!.length; i++) {
      let item = resData.dataMap1.get(state.currentMonth)!![i]
      let item2 = resData.dataMap2.get(state.currentMonth)!![i]
      let _item = i === 0 ? (lastMonthLast) : (resData.dataMap1.get(state.currentMonth)!![i - 1])
      let time = { value: item.time.slice(0, 16) }
      let price: any = {
        value: Lib.toFixedString(item.price, 1),
        placement: 'left',
        popover: {
          avg: Lib.toFixedString(item.priceAvg, 1),
        },
      }
      if (item.priceAvgChg !== 0) {
        price.popover.avgChg = Lib.toFixedString(item.priceAvgChg * 100, 2) + "%"
      }
      let isShow = true
      if (_item && !state.isShowAll && _item.state === Status.Hedge && item.state === Status.Hedge) {
        isShow = false
      }
      let status = item.state
      let status2 = item2.state
      let rate = Lib.toFixedString(item.s, 3)
      let rate2 = Lib.toFixedString(item2.s, 3)
      if (status !== status2) {
        price.popover.status2 = status2
      }
      if (rate !== rate2) {
        price.popover.rate2 = rate2
      }
      if (isShow) {
        items2.push({
          time, price, status: { value: status }, rate: { value: rate }
        })
      }
    }
    for (let i = items2.length - 1; i >= 0; i--) {
      if (items2[i].status.value === Status.Hedge && state.currentMonth === Lib.getNowStringTime().slice(0, 7)) {
        items2[i].time.popover = { value: resData.startTime.slice(0, 16) }
        items2[i].time.placement = 'top'
      }
      items2[i].status.value = Lib.toLowerCase(items2[i].status.value)
      if (items2[i].price?.popover?.status2) {
        items2[i].price.popover.status2 = Lib.toLowerCase(items2[i].price?.popover?.status2)
      }
    }
  }
  let table2 = { width, border: false, fields: fields2, items: items2 }
  state.table2 = table2
}

function setTable3() {
  let fields3 = [
    { key: 'lastNMonth', label: 'lastNMonth', align: 'center', width: 107 },
    { key: 'rate', label: 'rate', align: 'center' },
    { key: 'avgMonth', label: 'avgMonth', align: 'center', width: 96 },
  ]
  let items3: any[] = []
  for (let item of resData.lastNMonthSPerSixMonth1) {
    let item2 = resData.lastNMonthSPerSixMonth2.find(({ lastNMonth }) => {
      return lastNMonth === item.lastNMonth
    })
    items3.push({
      lastNMonth: {
        value: item.lastNMonth,
        placement: 'right',
        popover: { rate2: !item2 ? 1 : Lib.toFixedString(item2.totalS, 15) },
      },
      rate: { value: Lib.toFixedString(item.totalS, 1) },
      avgMonth: { value: Lib.toFixedString(item.monthAvgS, 3) },
    })
  }
  state.table3 = { width, border: true, fields: fields3, items: items3 }
}

function setTable4() {
  let fields4 = [
    { key: 'year', label: 'year', align: 'center' },
    { key: 'rate', label: 'rate', align: 'center' },
    { key: 'avgMonth', label: 'avgMonth', align: 'center' },
  ]
  let items4: any[] = []
  for (let [year, item] of resData.dataMapYearSMonthAvgS1.entries()) {
    let item2 = resData.dataMapYearSMonthAvgS2.get(year)
    items4.push({
      year: {
        value: year,
        placement: 'right',
        popover: { rate2: !item2 ? 1 : Lib.toFixedString(item2.yearTotalS, 15) },
      },
      rate: { value: Lib.toFixedString(item.yearTotalS, 2) },
      avgMonth: { value: Lib.toFixedString(item.monthAvgS, 3) },
    })
  }
  state.table4 = { width, border: true, fields: fields4, items: items4.reverse() }
}

async function getData() {
  Lib.getPrice(getPrice)
  resData = await Lib.getData()
  state.time = resData.analyseTime
  state.timeColor = resData.resErrorLogArray.length > 0 ? Color.red : Color.green
  let timeMin = Lib.getNowMilliTime() - Lib.stringTimeToMilliTime(resData.analyseTime)
  if (timeMin > 66 * 60 * 1000) {
    state.timeColor = Color.red
  }
  state.resErrorLogArray = resData.resErrorLogArray
  state.resInfoLogArray = resData.resInfoLogArray
  state.resPriceLog = resData.resPriceLog
  state.priceArray = []
  Array.from(resData.dataMap1.values()).at(-1)?.forEach((item) => {
    state.priceArray.push({ time: item.time, price: item.price })
  })
  if (state.resPriceLog?.shortPrice && state.resPriceLog?.time) {
    state.priceArray.push({ time: state.resPriceLog?.time, price: state.resPriceLog?.shortPrice })
  }
  state.isLoading = false
}

function getPrice(item: { time: string, price: number }) {
  if (state.priceArray.length === 0) {
    return
  }
  if (item.price === state.priceArray.at(-1)?.price) {
    state.priceArray.at(-1)!!.time = item.time
  } else {
    state.priceArray.push(item)
  }
  while (state.priceArray.length > 2) {
    state.priceArray.shift()
  }
}

</script>

<template>
  <div class="font" :style="{ 'min-width': width + 'px' }">
    <div v-if="state.isLoading" class="fc jcc aic" style="height: 100dvh;">
      <Loading></Loading>
    </div>
    <div v-else class="fc jcc aic">
      <div :style="{ 'width': width + 'px', 'height': '20px' }"></div>
      <TimeAndPrice :width="width" paddingLeft="5" paddingRight="5"
        :time="state.time ? `${state.time.slice(0, 16)} ${state.time.slice(-4)}` : ''" :timeColor="state.timeColor"
        :price="state.priceArray.at(-1) ? state.priceArray.at(-1)?.price : ''" :priceColor="state.priceColor">
      </TimeAndPrice>
      <div :style="{ 'width': width + 'px', 'height': '20px' }"></div>
      <MonthPicker @month-change="month => state.currentMonth = month" :width="width" paddingLeft="5" paddingRight="5">
      </MonthPicker>
      <div :style="{ 'width': width + 'px', 'height': '20px' }"></div>
      <Table v-if="state.table1" v-bind="state.table1"></Table>
      <div :style="{ 'width': width + 'px', 'height': '20px' }"></div>
      <Table v-if="state.table2" v-bind="state.table2"></Table>
      <div :style="{ 'width': width + 'px', 'height': '20px' }"></div>
      <Table v-if="state.table3" v-bind="state.table3"></Table>
      <div :style="{ 'width': width + 'px', 'height': '20px' }"></div>
      <Table v-if="state.table4" v-bind="state.table4"></Table>
      <div :style="{ 'width': width + 'px', 'height': '500px' }"></div>
    </div>
  </div>
</template>

<style scoped>
.font {
  font-family: Tahoma, Helvetica, Arial, "Hiragino Sans GB", "Microsoft YaHei", sans-serif;
}
</style>
